name: Check

on:
  push:
    paths:
      - 'parachain/common/**'
      - 'parachain/node/**'
      - 'parachain/pallets/**'
      - 'parachain/primitives/**'
      - 'parachain/runtime/**'
    branches:
      - main
  pull_request:
    paths:
      - 'parachain/common/**'
      - 'parachain/node/**'
      - 'parachain/pallets/**'
      - 'parachain/primitives/**'
      - 'parachain/runtime/**'

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('parachain/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - uses: actions/cache@v1
        with:
          path: parachain/target/debug
          key: ${{ runner.os }}-debug-build-${{ hashFiles('parachain/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-debug-build-
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: clippy
          target: wasm32-unknown-unknown
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path parachain/Cargo.toml
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path parachain/Cargo.toml
      - uses: actions/upload-artifact@v2
        with:
          path: world.txt